baseURL = "https://rominap22.github.io"
title = "YAPS"
theme = "hextra"
defaultContentLanguage = "en"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai"

[params.blog.list]
  displayTags = true

[[menu.main]]
  name = "Blog"
  pageRef = "/blog"
  weight = 1

[[menu.main]]
  name = "About"
  pageRef = "/about"
  weight = 2

